namespace Ebay2magento.Client.Entities
{
	public class EbayItemData
	{
		public string SiteID { get; set; }
		public string Format { get; set; }
		public string Title { get; set; }
		public string Condition { get; set; }
		public string ConditionDescription { get; set; }
		public string SubTitle { get; set; }
		public string CustomLabel { get; set; }
		public string Category { get; set; }
		public string Category2 { get; set; }
		public string StoreCategory { get; set; }
		public string StoreCategory2 { get; set; }
		public string Quantity { get; set; }
		public string LotSize { get; set; }
		public string Currency { get; set; }
		public string StartPrice { get; set; }
		public string BuyItNowPrice { get; set; }
		public string ReservePrice { get; set; }
		public string InsuranceOption { get; set; }
		public string InsuranceFee { get; set; }
		public string DomesticInsuranceOption { get; set; }
		public string DomesticInsuranceFee { get; set; }
		public string PackagingHandlingCosts { get; set; }
		public string InternationalPackagingHandlingCosts { get; set; }
		public string Duration { get; set; }
		public string PrivateAuction { get; set; }
		public string Country { get; set; }

		public string ItemID { get; set; }
		public string Description { get; set; }
		public string HitCounter { get; set; }
		public string PicURL { get; set; }
		public string BoldTitle { get; set; }
		public string Featured { get; set; }
		public string GalleryType { get; set; }
		public string FeaturedFirstDuration { get; set; }
		public string Highlight { get; set; }
		public string Border { get; set; }
		public string HomePageFeatured { get; set; }
		public string SalesTaxPercent { get; set; }
		public string SalesTaxState { get; set; }
		public string ShippingInTax { get; set; }
		public string UseTaxTable { get; set; }
		public string PostalCode { get; set; }
		public string ProxyItem { get; set; }
		public string VATPercent { get; set; }
		public string Location { get; set; }
		public string ImmediatePayRequired { get; set; }
		public string PayPalAccepted { get; set; }
		public string PayPalEmailAddress { get; set; }
		public string PaymentInstructions { get; set; }
		public string PaymateAccepted { get; set; }
		public string ProPayAccepted { get; set; }
		public string MoneyBookersAccepted { get; set; }
		public string StandardPayment { get; set; }
		public string UPC { get; set; }
		public string CCAccepted { get; set; }
		public string AmEx { get; set; }
		public string Discover { get; set; }
		public string VisaMastercard { get; set; }
		public string IntegratedMerchantCreditCard { get; set; }
		public string COD { get; set; }
		public string CODPrePayDelivery { get; set; }
		public string PostalTransfer { get; set; }
		public string MOCashiers { get; set; }
		public string PersonalCheck { get; set; }
		public string MoneyXferAccepted { get; set; }
		public string MoneyXferAcceptedinCheckout { get; set; }
		public string PaymentOther { get; set; }
		public string OtherOnlinePayments { get; set; }
		public string PaymentSeeDescription { get; set; }
		public string Escrow { get; set; }
		public string ShippingType { get; set; }
		public string GlobalShippingService { get; set; }
		public string ShipFromZipCode { get; set; }
		public string ShippingIrregular { get; set; }
		public string ShippingPackage { get; set; }
		public string WeightMajor { get; set; }
		public string WeightMinor { get; set; }
		public string WeightUnit { get; set; }
		public string MeasurementUnit { get; set; }
		public string PackageLength { get; set; }
		public string PackageWidth { get; set; }
		public string PackageDepth { get; set; }
		public string DomesticRateTable { get; set; }
		public string InternationalRateTable { get; set; }
		public string CharityID { get; set; }
		public string CharityName { get; set; }
		public string DonationPercent { get; set; }

		public string BasicUpgradePackBundle { get; set; }
		public string ValuePackBundle { get; set; }
		public string ProPackPlusBundle { get; set; }
		public string BestOfferEnabled { get; set; }
		public string AutoAccept { get; set; }
		public string BestOfferAutoAcceptPrice { get; set; }
		public string AutoDecline { get; set; }
		public string MinimumBestOfferPrice { get; set; }
		public string BestOfferRejectMessage { get; set; }
		public string LocalOnlyChk { get; set; }
		public string LocalListingDistance { get; set; }

		public string AdditionalDetails { get; set; }
		public string MarketplaceType { get; set; }
		public string ProjectGoodCategory { get; set; }
		public string ShortDescription { get; set; }
		public string ProducerDescription { get; set; }
		public string RegionOfOrigin { get; set; }
		public string ProducerPhotoURL { get; set; }
		//public string CBrand { get; set; }
		//public string CModel { get; set; }
		//public string CMPN { get; set; }
		public string Relationship { get; set; }
		public string RelationshipDetails { get; set; }
	}
}
